//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hastanerandevu.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hastaneEntities : DbContext
    {
        public hastaneEntities()
            : base("name=hastaneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<doktorlar> doktorlar { get; set; }
        public virtual DbSet<hastaneler> hastaneler { get; set; }
        public virtual DbSet<ilceler> ilceler { get; set; }
        public virtual DbSet<klinikler> klinikler { get; set; }
        public virtual DbSet<personel> personel { get; set; }
        public virtual DbSet<randevular> randevular { get; set; }
        public virtual DbSet<sehirler> sehirler { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tur> tur { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
